name: "Bushvin's PF2e Extension"
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Zip files
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* .vscode src'
    - name: Create Version Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.systemVersion }}
        allowUpdates: false
        draft: false
        prerelease: false
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.systemVersion }}

