name: "Bushvin's PF2e Extension"
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  fvtt_minimum: 11
  fvtt_verified: 11
  fvtt_dry_run: false
  fvtt_module_id: bushvin-pf2e-expansion

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'module.json'
      env:
        version: ${{ github.ref_name }}
        url: https://github.com/${{ github.repository }}
        manifest: https://github.com/${{ github.repository }}/releases/latest/download/module.json
        download: https://github.com/${{ github.repository }}/releases/latest/download/${{ env.fvtt_module_id }}.zip

    - name: Zip files
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: '${{ env.fvtt_module_id }}.zip'
        exclusions: '*.git* .vscode src'

    - name: Create Version Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.systemVersion }}
        allowUpdates: false
        draft: false
        prerelease: false
        artifacts: "module.json,${{ env.fvtt_module_id }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.systemVersion }}

